DROP DATABASE D2HDB;

CREATE DATABASE D2HDB;

CREATE TABLE D2H_USERS(
    UID INT PRIMARY KEY AUTO_INCREMENT,
    UNM VARCHAR(30) NOT NULL UNIQUE,
    PWD VARCHAR(25000) NOT NULL,
    ROLE VARCHAR(30) NOT NULL,
);

CREATE TABLE CONSUMERS(
    CSID INT PRIMARY KEY AUTO_INCREMENT,
    FNM VARCHAR(150) NOT NULL,
    LNM VARCHAR(150) NOT NULL,
    EML VARCHAR(200) NOT NULL,
    MBN CHAR(10) NOT NULL,
    DNO VARCHAR(20) NOT NULL,
    STRT VARCHAR(150) NOT NULL,
    CITY VARCHAR(150) NOT NULL,
    STATE VARCHAR(150) NOT NULL,
    PINC CHAR(6),
    WBAL NUMERIC NOT NULL,
    UID INT REFERENCES D2H_USERS(UID)
);

CREATE TABLE CHANNEL_CATEGORIES(
    CTID INT PRIMARY KEY AUTO_INCREMENT,
    CTNM VARCHAR(200) NOT NULL,
    DSCP VARCHAR(1000)
);

CREATE TABLE CHANNELS(
    CHID INT PRIMARY KEY AUTO_INCREMENT,
    CHNM VARCHAR(200) NOT NULL
);

CREATE TABLE PACKAGES(
    PKID INT PRIMARY KEY AUTO_INCREMENT,
    PKDN VARCHAR(150) NOT NULL,
    RATE NUMERIC NOT NULL
);

CREATE TABLE PACKAGE_DETAILS(
    PKID INT REFERENCES PACKAGES(PKID),
    CHID INT REFERENCES CHANNLES(CHID),
    PRIMARY KEY (PKID,CHID)
);

CREATE TABLE DISCOUNTS(
    DSID INT PRIMARY KEY AUTO_INCREMENT,
    PRCT NUMERIC NOT NULL,
    SDT DATE NOT NULL,
    EDT DATE NOT NULL,
    MAXC INT
);

CREATE TABLE SUBSCRIPTIONS(
    SRID INT PRIMARY KEY AUTO_INCREMENT,
    CSID INT REFERENCES CONSUMERS(CSID),
    PKID INT REFERENCES PACKAGES(PKID),
    SDT DATE,
    EDT DATE,
    -- GROSS TOTAL AMOUNT
    GTA NUMERIC,
    -- GST AMOUNT
    GST NUMERIC,
    -- DISCOUNT AMOUNT
    DSAMT NUMERIC,
    -- NET PAYABLE AMOUNT
    NPA NUMERIC,
    DSID INT REFERENCES DISCOUNTS(DSID)
);

CREATE TABLE TXNS(
    TXNID INT PRIMARY KEY AUTO_INCREMENT,
    AMT NUMERIC,
    TXNDT DATE,
    TXNTYPE INT,
    DSCP VARCHAR(250),
    CSID INT REFERENCES CONSUMERS(CSID)
);